import Navbar from "@/components/molecules/Navbar";
import "@/styles/globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} text-slate-700 px-6 pt-7 max-w-[1077px] mx-auto`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
